@startuml

' top to bottom direction
left to right direction

abstract BaseUser {
    +SearchRoutes()
}

class Guest {
}

class User {
    -id
    -email
    -password
    -passengers

    +AddPassenger(passenger)
    +EditPassenger(id)
    +BuyTicket(): Ticket
}

class SystemAdmin {
    +GetUsers()
    +GetUser(id)
    +EditUser(id)
    +DeleteUser(id)
    +TimeoutUser(id)
    +ResetUserPassword(id)
}

class ContentAdmin {
    +GetRoutes()
    +GetRoute(id)
    +EditRoute(id)
    +HideRoute(id)
    +ShowRoute(id)
    +DeleteRoute(id)
}

Guest -> BaseUser
User -> BaseUser
SystemAdmin -> User
ContentAdmin -> User

@enduml
